// Mocks generated by Mockito 5.4.6 from annotations
// in modern_gauge_flutter/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;
import 'dart:ui' as _i12;

import 'package:flutter/material.dart' as _i6;
import 'package:go_router/src/configuration.dart' as _i5;
import 'package:go_router/src/delegate.dart' as _i7;
import 'package:go_router/src/information_provider.dart' as _i8;
import 'package:go_router/src/match.dart' as _i20;
import 'package:go_router/src/parser.dart' as _i9;
import 'package:go_router/src/router.dart' as _i18;
import 'package:go_router/src/state.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;
import 'package:modern_gauge_flutter/models/dial_data.dart' as _i3;
import 'package:modern_gauge_flutter/models/ecu_data.dart' as _i10;
import 'package:modern_gauge_flutter/models/settings_data.dart' as _i2;
import 'package:modern_gauge_flutter/providers/app_state_provider.dart' as _i15;
import 'package:modern_gauge_flutter/providers/dial_provider.dart' as _i16;
import 'package:modern_gauge_flutter/providers/ecu_provider.dart' as _i21;
import 'package:modern_gauge_flutter/providers/settings_provider.dart' as _i11;
import 'package:modern_gauge_flutter/services/mpris_listener.dart' as _i17;
import 'package:modern_gauge_flutter/services/odb_service.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSettingsData_0 extends _i1.SmartFake implements _i2.SettingsData {
  _FakeSettingsData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDialData_1 extends _i1.SmartFake implements _i3.DialData {
  _FakeDialData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouterState_3 extends _i1.SmartFake implements _i4.GoRouterState {
  _FakeGoRouterState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteConfiguration_4 extends _i1.SmartFake
    implements _i5.RouteConfiguration {
  _FakeRouteConfiguration_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBackButtonDispatcher_5 extends _i1.SmartFake
    implements _i6.BackButtonDispatcher {
  _FakeBackButtonDispatcher_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouterDelegate_6 extends _i1.SmartFake
    implements _i7.GoRouterDelegate {
  _FakeGoRouterDelegate_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouteInformationProvider_7 extends _i1.SmartFake
    implements _i8.GoRouteInformationProvider {
  _FakeGoRouteInformationProvider_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouteInformationParser_8 extends _i1.SmartFake
    implements _i9.GoRouteInformationParser {
  _FakeGoRouteInformationParser_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEcuData_9 extends _i1.SmartFake implements _i10.EcuData {
  _FakeEcuData_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsProvider extends _i1.Mock implements _i11.SettingsProvider {
  MockSettingsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsData get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeSettingsData_0(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i2.SettingsData);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void updateSettings(_i2.SettingsData? newSettings) => super.noSuchMethod(
    Invocation.method(#updateSettings, [newSettings]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleSound(bool? enabled) => super.noSuchMethod(
    Invocation.method(#toggleSound, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void setBackgroundImage(String? path) => super.noSuchMethod(
    Invocation.method(#setBackgroundImage, [path]),
    returnValueForMissingStub: null,
  );

  @override
  void setScreenBrightness(double? brightness) => super.noSuchMethod(
    Invocation.method(#setScreenBrightness, [brightness]),
    returnValueForMissingStub: null,
  );

  @override
  void setThemeMode(_i6.ThemeMode? mode) => super.noSuchMethod(
    Invocation.method(#setThemeMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void setAutoSleepDelay(int? delaySeconds) => super.noSuchMethod(
    Invocation.method(#setAutoSleepDelay, [delaySeconds]),
    returnValueForMissingStub: null,
  );

  @override
  void setWakeUpMode(_i2.WakeUpMode? mode) => super.noSuchMethod(
    Invocation.method(#setWakeUpMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void resetSettings() => super.noSuchMethod(
    Invocation.method(#resetSettings, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OdbService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOdbService extends _i1.Mock implements _i13.OdbService {
  MockOdbService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Stream<_i3.DialData> get dataStream =>
      (super.noSuchMethod(
            Invocation.getter(#dataStream),
            returnValue: _i14.Stream<_i3.DialData>.empty(),
          )
          as _i14.Stream<_i3.DialData>);

  @override
  _i14.Stream<_i15.OdbConnectionStatus> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i14.Stream<_i15.OdbConnectionStatus>.empty(),
          )
          as _i14.Stream<_i15.OdbConnectionStatus>);

  @override
  void startOdbDataStream() => super.noSuchMethod(
    Invocation.method(#startOdbDataStream, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopOdbDataStream() => super.noSuchMethod(
    Invocation.method(#stopOdbDataStream, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DialProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialProvider extends _i1.Mock implements _i16.DialProvider {
  MockDialProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DialData get dialData =>
      (super.noSuchMethod(
            Invocation.getter(#dialData),
            returnValue: _FakeDialData_1(this, Invocation.getter(#dialData)),
          )
          as _i3.DialData);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void updateAllDialData(_i3.DialData? newData) => super.noSuchMethod(
    Invocation.method(#updateAllDialData, [newData]),
    returnValueForMissingStub: null,
  );

  @override
  void updateRpm(double? rpm) => super.noSuchMethod(
    Invocation.method(#updateRpm, [rpm]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSpeed(double? speed) => super.noSuchMethod(
    Invocation.method(#updateSpeed, [speed]),
    returnValueForMissingStub: null,
  );

  @override
  void updateCoolantTemp(double? temp) => super.noSuchMethod(
    Invocation.method(#updateCoolantTemp, [temp]),
    returnValueForMissingStub: null,
  );

  @override
  void updateFuelLevel(double? level) => super.noSuchMethod(
    Invocation.method(#updateFuelLevel, [level]),
    returnValueForMissingStub: null,
  );

  @override
  void updateOilPressure(double? pressure) => super.noSuchMethod(
    Invocation.method(#updateOilPressure, [pressure]),
    returnValueForMissingStub: null,
  );

  @override
  void updateBatteryVoltage(double? voltage) => super.noSuchMethod(
    Invocation.method(#updateBatteryVoltage, [voltage]),
    returnValueForMissingStub: null,
  );

  @override
  void updateOdometer(double? odometer) => super.noSuchMethod(
    Invocation.method(#updateOdometer, [odometer]),
    returnValueForMissingStub: null,
  );

  @override
  void resetDialData() => super.noSuchMethod(
    Invocation.method(#resetDialData, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MprisListener].
///
/// See the documentation for Mockito's code generation for more information.
class MockMprisListener extends _i1.Mock implements _i17.MprisListener {
  MockMprisListener() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get position =>
      (super.noSuchMethod(
            Invocation.getter(#position),
            returnValue: _FakeDuration_2(this, Invocation.getter(#position)),
          )
          as Duration);

  @override
  _i17.PlaybackStatus get playbackStatus =>
      (super.noSuchMethod(
            Invocation.getter(#playbackStatus),
            returnValue: _i17.PlaybackStatus.playing,
          )
          as _i17.PlaybackStatus);

  @override
  bool get isPlaying =>
      (super.noSuchMethod(Invocation.getter(#isPlaying), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i14.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [AppStateProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppStateProvider extends _i1.Mock implements _i15.AppStateProvider {
  MockAppStateProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAsleep =>
      (super.noSuchMethod(Invocation.getter(#isAsleep), returnValue: false)
          as bool);

  @override
  _i15.OdbConnectionStatus get odbStatus =>
      (super.noSuchMethod(
            Invocation.getter(#odbStatus),
            returnValue: _i15.OdbConnectionStatus.disconnected,
          )
          as _i15.OdbConnectionStatus);

  @override
  bool get isInitializing =>
      (super.noSuchMethod(
            Invocation.getter(#isInitializing),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setSleepMode(bool? asleep) => super.noSuchMethod(
    Invocation.method(#setSleepMode, [asleep]),
    returnValueForMissingStub: null,
  );

  @override
  void setOdbConnectionStatus(_i15.OdbConnectionStatus? status) =>
      super.noSuchMethod(
        Invocation.method(#setOdbConnectionStatus, [status]),
        returnValueForMissingStub: null,
      );

  @override
  void finishInitialization() => super.noSuchMethod(
    Invocation.method(#finishInitialization, []),
    returnValueForMissingStub: null,
  );

  @override
  void setGlobalAlert(String? message) => super.noSuchMethod(
    Invocation.method(#setGlobalAlert, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GoRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoRouter extends _i1.Mock implements _i18.GoRouter {
  MockGoRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GoRouterState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeGoRouterState_3(this, Invocation.getter(#state)),
          )
          as _i4.GoRouterState);

  @override
  _i5.RouteConfiguration get configuration =>
      (super.noSuchMethod(
            Invocation.getter(#configuration),
            returnValue: _FakeRouteConfiguration_4(
              this,
              Invocation.getter(#configuration),
            ),
          )
          as _i5.RouteConfiguration);

  @override
  _i6.BackButtonDispatcher get backButtonDispatcher =>
      (super.noSuchMethod(
            Invocation.getter(#backButtonDispatcher),
            returnValue: _FakeBackButtonDispatcher_5(
              this,
              Invocation.getter(#backButtonDispatcher),
            ),
          )
          as _i6.BackButtonDispatcher);

  @override
  _i7.GoRouterDelegate get routerDelegate =>
      (super.noSuchMethod(
            Invocation.getter(#routerDelegate),
            returnValue: _FakeGoRouterDelegate_6(
              this,
              Invocation.getter(#routerDelegate),
            ),
          )
          as _i7.GoRouterDelegate);

  @override
  _i8.GoRouteInformationProvider get routeInformationProvider =>
      (super.noSuchMethod(
            Invocation.getter(#routeInformationProvider),
            returnValue: _FakeGoRouteInformationProvider_7(
              this,
              Invocation.getter(#routeInformationProvider),
            ),
          )
          as _i8.GoRouteInformationProvider);

  @override
  _i9.GoRouteInformationParser get routeInformationParser =>
      (super.noSuchMethod(
            Invocation.getter(#routeInformationParser),
            returnValue: _FakeGoRouteInformationParser_8(
              this,
              Invocation.getter(#routeInformationParser),
            ),
          )
          as _i9.GoRouteInformationParser);

  @override
  bool get overridePlatformDefaultLocation =>
      (super.noSuchMethod(
            Invocation.getter(#overridePlatformDefaultLocation),
            returnValue: false,
          )
          as bool);

  @override
  set configuration(_i5.RouteConfiguration? value) => super.noSuchMethod(
    Invocation.setter(#configuration, value),
    returnValueForMissingStub: null,
  );

  @override
  set routerDelegate(_i7.GoRouterDelegate? value) => super.noSuchMethod(
    Invocation.setter(#routerDelegate, value),
    returnValueForMissingStub: null,
  );

  @override
  set routeInformationProvider(_i8.GoRouteInformationProvider? value) =>
      super.noSuchMethod(
        Invocation.setter(#routeInformationProvider, value),
        returnValueForMissingStub: null,
      );

  @override
  set routeInformationParser(_i9.GoRouteInformationParser? value) =>
      super.noSuchMethod(
        Invocation.setter(#routeInformationParser, value),
        returnValueForMissingStub: null,
      );

  @override
  bool canPop() =>
      (super.noSuchMethod(Invocation.method(#canPop, []), returnValue: false)
          as bool);

  @override
  String namedLocation(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    String? fragment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #namedLocation,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #fragment: fragment,
              },
            ),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.method(
                #namedLocation,
                [name],
                {
                  #pathParameters: pathParameters,
                  #queryParameters: queryParameters,
                  #fragment: fragment,
                },
              ),
            ),
          )
          as String);

  @override
  void go(String? location, {Object? extra}) => super.noSuchMethod(
    Invocation.method(#go, [location], {#extra: extra}),
    returnValueForMissingStub: null,
  );

  @override
  void restore(_i20.RouteMatchList? matchList) => super.noSuchMethod(
    Invocation.method(#restore, [matchList]),
    returnValueForMissingStub: null,
  );

  @override
  void goNamed(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
    String? fragment,
  }) => super.noSuchMethod(
    Invocation.method(
      #goNamed,
      [name],
      {
        #pathParameters: pathParameters,
        #queryParameters: queryParameters,
        #extra: extra,
        #fragment: fragment,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<T?> push<T extends Object?>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
            Invocation.method(#push, [location], {#extra: extra}),
            returnValue: _i14.Future<T?>.value(),
          )
          as _i14.Future<T?>);

  @override
  _i14.Future<T?> pushNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i14.Future<T?>.value(),
          )
          as _i14.Future<T?>);

  @override
  _i14.Future<T?> pushReplacement<T extends Object?>(
    String? location, {
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pushReplacement, [location], {#extra: extra}),
            returnValue: _i14.Future<T?>.value(),
          )
          as _i14.Future<T?>);

  @override
  _i14.Future<T?> pushReplacementNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushReplacementNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i14.Future<T?>.value(),
          )
          as _i14.Future<T?>);

  @override
  _i14.Future<T?> replace<T>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
            Invocation.method(#replace, [location], {#extra: extra}),
            returnValue: _i14.Future<T?>.value(),
          )
          as _i14.Future<T?>);

  @override
  _i14.Future<T?> replaceNamed<T>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i14.Future<T?>.value(),
          )
          as _i14.Future<T?>);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#pop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [EcuProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockEcuProvider extends _i1.Mock implements _i21.EcuProvider {
  MockEcuProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.EcuData get currentData =>
      (super.noSuchMethod(
            Invocation.getter(#currentData),
            returnValue: _FakeEcuData_9(this, Invocation.getter(#currentData)),
          )
          as _i10.EcuData);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i14.Future<void> setEcuType(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setEcuType, [name]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> setSerialPort(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setSerialPort, [name]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> sendCommand(String? command) =>
      (super.noSuchMethod(
            Invocation.method(#sendCommand, [command]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
